# Generated by Django 4.1.7 on 2023-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='defaults/user_avatar_1.webp', upload_to='accounts/avatars/', verbose_name='Avatar'),
        ),
    ]
