# Generated by Django 4.1.7 on 2023-03-09 10:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(default='defaults/post_banner.webp', upload_to='blog/posts/', verbose_name='Post Banner')),
                ('title', models.CharField(max_length=225, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=885, verbose_name='Post Description')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime Modified')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Post Content')),
                ('pub_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publish Datetime')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', max_length=1, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Post Category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
