# Generated by Django 4.1.7 on 2023-03-09 23:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, help_text='The description of this category can have a great impact on the process of editing, deleting, adding and naming it.', verbose_name='Category Content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The "Active" option can stop posts from being shown to the public.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='You can choose a name for this category. This name is displayed when a post is read.', max_length=225, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='defaults/post_banner.webp', help_text='The post banner is a field that is shown to the user next to the post title in any case and is completely different from other photos of the post content.', upload_to='blog/posts/', verbose_name='Post Banner'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(help_text='Choose a category related to the content of the post for the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='This part of the post is the body and full content of the post. Here you are not limited by any special rules and you can type as much as you want. Remember, your only limitation is offensive words. It is not acceptable to post offensive words on the site. Apart from this, in addition to the text, you can upload any file you want.', verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='The description of this post is shown for SEO and as a summary of this post and its content in the list of posts. The quality of literature and writing in this field is very important.', max_length=885, verbose_name='Post Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The "Active" option can stop posts from being shown to the public.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The title of the post does not need additional explanation, just remind me that it should be short and concise.', max_length=225, verbose_name='Title'),
        ),
    ]
