# Generated by Django 4.1.7 on 2023-03-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='Slugs are fields for addressing and are very important in SEO as well as site performance. Preferably, Slug should be English and meaningful.', max_length=225, unique=True, verbose_name='Slug'),
        ),
    ]
