# Generated by Django 4.1.7 on 2023-03-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='The description of this post is shown for SEO and as a summary of this post and its content in the list of posts. The quality of literature and writing in this field is very important.', max_length=885, unique=True, verbose_name='Post Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The title of the post does not need additional explanation, just remind me that it should be short and concise.', max_length=225, unique=True, verbose_name='Title'),
        ),
    ]
