# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_pub_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publish Datetime'),
        ),
    ]
